#!/bin/bash
wget --content-disposition http://ligman.me/1IW1oab		
wget --content-disposition http://ligman.me/1Uixtlq		
wget --content-disposition http://ligman.me/1R9Ubgt		
wget --content-disposition http://ligman.me/1H4VXHT		
wget --content-disposition http://ligman.me/1f8XUKy		
wget --content-disposition http://ligman.me/1HBEUPi		
wget --content-disposition http://ligman.me/1NDTZR4		
wget --content-disposition http://ligman.me/1Uiy2f9		
wget --content-disposition http://ligman.me/1epZ0QU		
wget --content-disposition http://ligman.me/1JIhgjA		
wget --content-disposition http://ligman.me/1CQX5uG		
wget --content-disposition http://ligman.me/1JD5Q3i		
wget --content-disposition http://ligman.me/2sUanwC		
wget --content-disposition http://ligman.me/2twPBSD		
wget --content-disposition http://ligman.me/2tE7q0i		
wget --content-disposition http://ligman.me/2t2y29a		
wget --content-disposition http://ligman.me/2tJ1pj4		
wget --content-disposition http://ligman.me/2u2KdXT		
wget --content-disposition http://ligman.me/1IW1s9S		
wget --content-disposition http://ligman.me/1UixANR		
wget --content-disposition http://ligman.me/1f8Xvri		
wget --content-disposition http://ligman.me/2tEn8Zy		
wget --content-disposition http://ligman.me/2tEbPAp		
wget --content-disposition http://ligman.me/2u0WD2F		
wget --content-disposition http://ligman.me/2t2FyB9		
wget --content-disposition http://ligman.me/2uGi1Ig		
wget --content-disposition http://ligman.me/2t2Ghm1		
wget --content-disposition http://ligman.me/2sLiBTE		
wget --content-disposition http://ligman.me/1gfeQ27		
wget --content-disposition http://ligman.me/1KBM8DL		
wget --content-disposition http://ligman.me/1GVxKR6		
wget --content-disposition http://ligman.me/1KBM1YL		
wget --content-disposition http://ligman.me/2v7M0bp		
wget --content-disposition http://ligman.me/1dDcwQC		
wget --content-disposition http://ligman.me/1LIQw4D		
wget --content-disposition http://ligman.me/1HCWJ2c		
wget --content-disposition http://ligman.me/2u1190V		
wget --content-disposition http://ligman.me/2sE8dNG		
wget --content-disposition http://ligman.me/2twPKVT		
wget --content-disposition http://ligman.me/1NErkvl		
wget --content-disposition http://ligman.me/1KyWplK		
wget --content-disposition http://ligman.me/1RabduO		
wget --content-disposition http://ligman.me/1epZeHO		
wget --content-disposition http://ligman.me/2tE9hCx		
wget --content-disposition http://ligman.me/2uFU3wF		
wget --content-disposition http://ligman.me/2t2WqaR		
wget --content-disposition http://ligman.me/2sUA9kk		
wget --content-disposition http://ligman.me/1CQXMEp		
wget --content-disposition http://ligman.me/1JITgwM		
wget --content-disposition http://ligman.me/1RaaZny		
wget --content-disposition http://ligman.me/2uZg49h		
wget --content-disposition http://ligman.me/1LN5APL		
wget --content-disposition http://ligman.me/1GVx0eW		
wget --content-disposition http://ligman.me/1dD5sDy		
wget --content-disposition http://ligman.me/1RWzfoe		
wget --content-disposition http://ligman.me/1JDj7Jl		
wget --content-disposition http://ligman.me/1f9bOfu		
wget --content-disposition http://ligman.me/1LNdusd		
wget --content-disposition http://ligman.me/1KyWLZv		
wget --content-disposition http://ligman.me/2tEKIoU		
wget --content-disposition http://ligman.me/2uGZkV1		
wget --content-disposition http://ligman.me/2tJAEuU		
wget --content-disposition http://ligman.me/1odT1MW		
wget --content-disposition http://ligman.me/1NJ0vpb		
wget --content-disposition http://ligman.me/1dHBtdA		
wget --content-disposition http://ligman.me/1NIYrxw		
wget --content-disposition http://ligman.me/1qNYIYi		
wget --content-disposition http://ligman.me/1rH9Ar3		
wget --content-disposition http://ligman.me/1kvWKEm		
wget --content-disposition http://ligman.me/1m8yCMD		
wget --content-disposition http://ligman.me/1kvXrxj		
wget --content-disposition http://ligman.me/1pUnYfG		
wget --content-disposition http://ligman.me/1CWgeLI		
wget --content-disposition http://ligman.me/2v0ShWr		
wget --content-disposition http://ligman.me/2sF6M19		
wget --content-disposition http://ligman.me/2sVh6qf		
wget --content-disposition http://ligman.me/2tYdqU8		
wget --content-disposition http://ligman.me/1oB9ptL		
wget --content-disposition http://ligman.me/2sFbbl0		
wget --content-disposition http://ligman.me/2v1ok8u		
wget --content-disposition http://ligman.me/1HIcIKB		
wget --content-disposition http://ligman.me/1Cl328D		
wget --content-disposition http://ligman.me/VSpodw		
wget --content-disposition http://ligman.me/1S36CGa		
wget --content-disposition http://ligman.me/2tEPKBF		
wget --content-disposition http://ligman.me/2sVSiyp		
wget --content-disposition http://ligman.me/2tEHPV9		
wget --content-disposition http://ligman.me/2t3xIav		
wget --content-disposition http://ligman.me/1H1MFKr		
wget --content-disposition http://ligman.me/2u2bSbh		
wget --content-disposition http://ligman.me/2u7XYoT		
wget --content-disposition http://ligman.me/2txAWqi		
wget --content-disposition http://ligman.me/1sgBtn4		
wget --content-disposition http://ligman.me/2tEnvmU		
wget --content-disposition http://ligman.me/2txxLic		
wget --content-disposition http://ligman.me/2u89sJ3		
wget --content-disposition http://ligman.me/1qzON6Q		
wget --content-disposition http://ligman.me/2tXYR34		
wget --content-disposition http://ligman.me/1onTg9n		
wget --content-disposition http://ligman.me/2uH1nrZ		
wget --content-disposition http://ligman.me/VP2t2L		
wget --content-disposition http://ligman.me/2v0u0jd		
wget --content-disposition http://ligman.me/1dD6v6s		
wget --content-disposition http://ligman.me/1Ra595J		
wget --content-disposition http://ligman.me/2v0H3ku		
wget --content-disposition http://ligman.me/2tEtms3		
wget --content-disposition http://ligman.me/2u88i06		
wget --content-disposition http://ligman.me/1jWMJA2		
wget --content-disposition http://ligman.me/1qZlnOJ		
wget --content-disposition http://ligman.me/2u2RnLQ		
wget --content-disposition http://ligman.me/2v0AQFy		
wget --content-disposition http://ligman.me/1xqtaWN		
wget --content-disposition http://ligman.me/2v0v72p		
wget --content-disposition http://ligman.me/1HCDxl9		
wget --content-disposition http://ligman.me/2u7Lw8N		
wget --content-disposition http://ligman.me/1HByNKS		
wget --content-disposition http://ligman.me/29a22WR		
wget --content-disposition http://ligman.me/29bcJtd		
wget --content-disposition http://ligman.me/29rwoHw		
wget --content-disposition http://ligman.me/2sF7s6H		
wget --content-disposition http://ligman.me/1CSMobd		
wget --content-disposition http://ligman.me/29d5XTw		
wget --content-disposition http://ligman.me/29rwoY0		
wget --content-disposition http://ligman.me/29d1wc3		
wget --content-disposition http://ligman.me/29fudHc		
wget --content-disposition http://ligman.me/1FYtDD8		
wget --content-disposition http://ligman.me/29hVdVa		
wget --content-disposition http://ligman.me/29fDult		
wget --content-disposition http://ligman.me/29cfePX		
wget --content-disposition http://ligman.me/1NCfcKC		
wget --content-disposition http://ligman.me/29fDylj		
wget --content-disposition http://ligman.me/29fDylj		
wget --content-disposition http://ligman.me/29d5AbX		
wget --content-disposition http://ligman.me/1JI6V77		
wget --content-disposition http://ligman.me/1H4Q0e5		
wget --content-disposition http://ligman.me/1LMpRns		
wget --content-disposition http://ligman.me/1HCCCRP		
wget --content-disposition http://ligman.me/29FzGG5		
wget --content-disposition http://ligman.me/29e6cTO		
wget --content-disposition http://ligman.me/29gfrkN		
wget --content-disposition http://ligman.me/1Ra5c1c		
wget --content-disposition http://ligman.me/29vGIvY		
wget --content-disposition http://ligman.me/2sVGUSX		
wget --content-disposition http://ligman.me/2u1KmL9		
wget --content-disposition http://ligman.me/1n49kzj		
wget --content-disposition http://ligman.me/1qZlFVR		
wget --content-disposition http://ligman.me/TWa2Dg		
wget --content-disposition http://ligman.me/1xzdEtT		
wget --content-disposition http://ligman.me/1HCQyeA		
wget --content-disposition http://ligman.me/1Cg5iOv		
wget --content-disposition http://ligman.me/2sUC4FK		
wget --content-disposition http://ligman.me/2u12ggX		
wget --content-disposition http://ligman.me/1onU8Ld		
wget --content-disposition http://ligman.me/1vM9mwt		
wget --content-disposition http://ligman.me/1rB8nl1		
wget --content-disposition http://ligman.me/1JDjqUt		
wget --content-disposition http://ligman.me/1eqdXCI		
wget --content-disposition http://ligman.me/1Uj0hu2		
wget --content-disposition http://ligman.me/2tYk9gX		
wget --content-disposition http://ligman.me/2tYk9gX		
wget --content-disposition http://ligman.me/2sVrsGy		
wget --content-disposition http://ligman.me/1M7Xr5v		
wget --content-disposition http://ligman.me/2t3nqXV		
wget --content-disposition http://ligman.me/2u2K9aI		
wget --content-disposition http://ligman.me/1vM9H2d		
wget --content-disposition http://ligman.me/2sFsnXy		
wget --content-disposition http://ligman.me/1m6xucg		
wget --content-disposition http://ligman.me/1qzRntH		
wget --content-disposition http://ligman.me/1lJmKeW		
wget --content-disposition http://ligman.me/29ZNaMN		
wget --content-disposition http://ligman.me/2tEERQt		
wget --content-disposition http://ligman.me/29sp3nZ		
wget --content-disposition http://ligman.me/29LXmMt		
wget --content-disposition http://ligman.me/29EmfZc		
wget --content-disposition http://ligman.me/2t3HOIt		
wget --content-disposition http://ligman.me/2tE789y		
wget --content-disposition http://ligman.me/2sUDY9j		
wget --content-disposition http://ligman.me/2tEI5U4		
wget --content-disposition http://ligman.me/29yWFFf		
wget --content-disposition http://ligman.me/2tEtGXW		
wget --content-disposition http://ligman.me/2txJKMz		
wget --content-disposition http://ligman.me/2uH1kN1		
wget --content-disposition http://ligman.me/2tY8L4x		
wget --content-disposition http://ligman.me/2tyf2TJ		
wget --content-disposition http://ligman.me/2v0CY01		
wget --content-disposition http://ligman.me/2v0vXMn		
wget --content-disposition http://ligman.me/2u8l13d		
wget --content-disposition http://ligman.me/2u8jZEr		
wget --content-disposition http://ligman.me/1omCrM6		
wget --content-disposition http://ligman.me/2sFvbUs		
wget --content-disposition http://ligman.me/2tYmSHb		
wget --content-disposition http://ligman.me/1n3mkVY		
wget --content-disposition http://ligman.me/2tEXUKw		
wget --content-disposition http://ligman.me/2tEAt3Z		
wget --content-disposition http://ligman.me/2t3uPGw		
wget --content-disposition http://ligman.me/2uFTByu		
wget --content-disposition http://ligman.me/2tXvePt		
wget --content-disposition http://ligman.me/12FIZ1I		
wget --content-disposition http://ligman.me/2v0Dhb1		
wget --content-disposition http://ligman.me/2u0QCD2		
wget --content-disposition http://ligman.me/2sEzMGA		
wget --content-disposition http://ligman.me/2u8h5PG		
wget --content-disposition http://ligman.me/2uGN9ao		
wget --content-disposition http://ligman.me/TL3pn1		
wget --content-disposition http://ligman.me/2txHeGo		
wget --content-disposition http://ligman.me/29FkNr3		
wget --content-disposition http://ligman.me/1anyEJj		
wget --content-disposition http://ligman.me/N1HEpM		
wget --content-disposition http://ligman.me/2sVpUwk		
wget --content-disposition http://ligman.me/2u8ao0i		
wget --content-disposition http://ligman.me/2u7MT7t		
wget --content-disposition http://ligman.me/2u89lNQ		
wget --content-disposition http://ligman.me/1ReR3Qq		
wget --content-disposition http://ligman.me/1RWzIGZ		
wget --content-disposition http://ligman.me/1CQXzkt		
wget --content-disposition http://ligman.me/1HBRMVs		
wget --content-disposition http://ligman.me/2u2j5sf		
wget --content-disposition http://ligman.me/1gfab07		
wget --content-disposition http://ligman.me/1JIDq58		
wget --content-disposition http://ligman.me/1KBMoTl		
wget --content-disposition http://ligman.me/1C7dU9J		
wget --content-disposition http://ligman.me/1GVycPq		
wget --content-disposition http://ligman.me/1LIJflp		
wget --content-disposition http://ligman.me/2u7ml6r		
wget --content-disposition http://ligman.me/2tXqzgh		
wget --content-disposition http://ligman.me/2u0ZCYU		
wget --content-disposition http://ligman.me/2t2o340		
wget --content-disposition http://ligman.me/2txRCxI		
wget --content-disposition http://ligman.me/1CQXzko		
wget --content-disposition http://ligman.me/1KyNJvs		
wget --content-disposition http://ligman.me/1C7dEYi		
wget --content-disposition http://ligman.me/1IzBL34		
wget --content-disposition http://ligman.me/29pcQFA		
wget --content-disposition http://ligman.me/N1J8A8		
wget --content-disposition http://ligman.me/N1JfvI		
wget --content-disposition http://ligman.me/16E6G9L		
wget --content-disposition http://ligman.me/16dHXZ9		
wget --content-disposition http://ligman.me/1S1f34H		
wget --content-disposition http://ligman.me/2sFqolM		
wget --content-disposition http://ligman.me/2tEHwtq		
wget --content-disposition http://ligman.me/2uGQTc7		
wget --content-disposition http://ligman.me/2u7TbUy		
wget --content-disposition http://ligman.me/2tYmEzR		
wget --content-disposition http://ligman.me/2tYaW8d		
wget --content-disposition http://ligman.me/2u2HKg6		
wget --content-disposition http://ligman.me/2tEHLVm		
wget --content-disposition http://ligman.me/11IMDlh		
wget --content-disposition http://ligman.me/29i2CEe		
wget --content-disposition http://ligman.me/29hofVk		
wget --content-disposition http://ligman.me/2sVrwWU		
wget --content-disposition http://ligman.me/2u2uvvZ		
wget --content-disposition http://ligman.me/1dD6S0J		
wget --content-disposition http://ligman.me/1NEgrJQ		
wget --content-disposition http://ligman.me/1IzC1z4		
wget --content-disposition http://ligman.me/2sUch05		
wget --content-disposition http://ligman.me/2twxADW		
wget --content-disposition http://ligman.me/2sEqaM0		
wget --content-disposition http://ligman.me/1JDrhBp		
wget --content-disposition http://ligman.me/1RWFCrK		
wget --content-disposition http://ligman.me/1M05t0d		
wget --content-disposition http://ligman.me/1C7okGv		
wget --content-disposition http://ligman.me/1UjcLBK		
wget --content-disposition http://ligman.me/1HBYNpg		
wget --content-disposition http://ligman.me/1KBVfnS		
wget --content-disposition http://ligman.me/1IzIbPR		
wget --content-disposition http://ligman.me/1HBYYRF		
wget --content-disposition http://ligman.me/1IzHZA1		
wget --content-disposition http://ligman.me/1RWFd8K		
wget --content-disposition http://ligman.me/1HCW4Or		
wget --content-disposition http://ligman.me/1GUUqSD		
wget --content-disposition http://ligman.me/1Cg8UQs		
wget --content-disposition http://ligman.me/1KyVGkv		
wget --content-disposition http://ligman.me/1CQXNbj		
wget --content-disposition http://ligman.me/1M05ktI		
wget --content-disposition http://ligman.me/1Ujd8fL		
wget --content-disposition http://ligman.me/1GUOZ6b		
wget --content-disposition http://ligman.me/1HCR2l0		
wget --content-disposition http://ligman.me/1FYOjLl		
wget --content-disposition http://ligman.me/1GUP0qL		
wget --content-disposition http://ligman.me/1GVyNAv		
wget --content-disposition http://ligman.me/1HBSfqC		
wget --content-disposition http://ligman.me/1KBMN8a		
wget --content-disposition http://ligman.me/1HCQQCb		
wget --content-disposition http://ligman.me/1Uj1dyo		
wget --content-disposition http://ligman.me/1f9cKQZ		
wget --content-disposition http://ligman.me/1RWzUWP		
wget --content-disposition http://ligman.me/1LIJxJ0		
wget --content-disposition http://ligman.me/1gfaIzh		
wget --content-disposition http://ligman.me/1LIJHA5		
wget --content-disposition http://ligman.me/1HCQXxv		
wget --content-disposition http://ligman.me/1JIF6vB		
wget --content-disposition http://ligman.me/1TaxTZD		
wget --content-disposition http://ligman.me/1TaxTJ5		
wget --content-disposition http://ligman.me/1M00Lzu		
wget --content-disposition http://ligman.me/1Cg5xc8		
wget --content-disposition http://ligman.me/1IWkjlf		
wget --content-disposition http://ligman.me/1M00v3u		
wget --content-disposition http://ligman.me/1GUOMzL		
wget --content-disposition http://ligman.me/1TaxqXr		
wget --content-disposition http://ligman.me/2t3NaDl		
wget --content-disposition http://ligman.me/1M05yAY		
wget --content-disposition http://ligman.me/1eql6Ts		
wget --content-disposition http://ligman.me/2sE9XX1		
wget --content-disposition http://ligman.me/2uZgfBj		
wget --content-disposition http://ligman.me/2tDZAUn		
wget --content-disposition http://ligman.me/2twLeqF		
wget --content-disposition http://ligman.me/2sF5tQ8		
wget --content-disposition http://ligman.me/2t2WmYx		
wget --content-disposition http://ligman.me/2uZiHI3		
wget --content-disposition http://ligman.me/2t2qX8T		
wget --content-disposition http://ligman.me/1Uiyx8Q		
wget --content-disposition http://ligman.me/1C6Tg9G		
wget --content-disposition http://ligman.me/1HCIlqM		
wget --content-disposition http://ligman.me/1JDrMeG		
wget --content-disposition http://ligman.me/1GVGV3U		
wget --content-disposition http://ligman.me/1JDrIvt		
wget --content-disposition http://ligman.me/1GVGQgI		
wget --content-disposition http://ligman.me/1RWFVCS		
wget --content-disposition http://ligman.me/1RWFUig		
wget --content-disposition http://ligman.me/2txIfxW		
wget --content-disposition http://ligman.me/2sVHDUg		
wget --content-disposition http://ligman.me/2u2R83b		
wget --content-disposition http://ligman.me/29ErxWs		
wget --content-disposition http://ligman.me/29yWAAO		
wget --content-disposition http://ligman.me/2sFzkaR		
wget --content-disposition http://ligman.me/2u12Nj7		
wget --content-disposition http://ligman.me/2uFUOG1		
wget --content-disposition http://ligman.me/2twRrCJ		
wget --content-disposition http://ligman.me/2t2mx1M		
wget --content-disposition http://ligman.me/2t2cYjp		
wget --content-disposition http://ligman.me/2twtAmW		
wget --content-disposition http://ligman.me/2u0YnZu		
wget --content-disposition http://ligman.me/2u15CAR		
wget --content-disposition http://ligman.me/1sfkqBW		
wget --content-disposition http://ligman.me/2txOv8Z		
wget --content-disposition http://ligman.me/1M06aXa		
wget --content-disposition http://ligman.me/1FYVYcy		
wget --content-disposition http://ligman.me/1dDcZ5h		
wget --content-disposition http://ligman.me/1H5ajbj		
wget --content-disposition http://ligman.me/1M0681D		
wget --content-disposition http://ligman.me/1UjeQh2		
wget --content-disposition http://ligman.me/1JIV1Kk		
wget --content-disposition http://ligman.me/1NErPpa		
wget --content-disposition http://ligman.me/1eqlNMp		
wget --content-disposition http://ligman.me/1NCxHi5		
wget --content-disposition http://ligman.me/1KBX7Nw		
wget --content-disposition http://ligman.me/1IzJ6Qp		
wget --content-disposition http://ligman.me/2uFKRZd		
wget --content-disposition http://ligman.me/2tDMJl0		
wget --content-disposition http://ligman.me/2uFDelL		
wget --content-disposition http://ligman.me/2twmtKY		
wget --content-disposition http://ligman.me/1f9k8fe		
wget --content-disposition http://ligman.me/1eqm4za		
wget --content-disposition http://ligman.me/2tXBiHF		
wget --content-disposition http://ligman.me/2v1cDyG		
wget --content-disposition http://ligman.me/2txRQFd		
wget --content-disposition http://ligman.me/2v1zdYa		
wget --content-disposition http://ligman.me/2sW0A9v		
wget --content-disposition http://ligman.me/2txQLgl		
wget --content-disposition http://ligman.me/2sFbVq3		
