Invoke-WebRequest http://ligman.me/1IW1oab -OutFile "Introducing Windows Azure for IT Professionals.pdf"
Invoke-WebRequest http://ligman.me/1H4VXHT -OutFile "Microsoft Azure Essentials Azure Automation.pdf"
Invoke-WebRequest http://ligman.me/1NDTZR4 -OutFile "Microsoft Azure Essentials Azure Machine Learning.pdf"
Invoke-WebRequest http://ligman.me/1JIhgjA -OutFile "Microsoft Azure Essentials Fundamentals of Azure.pdf"
Invoke-WebRequest http://ligman.me/2sUanwC -OutFile "Microsoft Azure Essentials Fundamentals of Azure, Second Edition.pdf"
Invoke-WebRequest http://ligman.me/2twPBSD -OutFile "Microsoft Azure Essentials Fundamentals of Azure, Second Edition Mobile.pdf"
Invoke-WebRequest http://ligman.me/2tE7q0i -OutFile "Microsoft Azure Essentials Migrating SQL Server Databases to Azure - Mobile.pdf"
Invoke-WebRequest http://ligman.me/2t2y29a -OutFile "Microsoft Azure Essentials Migrating SQL Server Databases to Azure 8.5X11.pdf"
Invoke-WebRequest http://ligman.me/2tJ1pj4 -OutFile "Microsoft Azure ExpressRoute Guide.pdf"
Invoke-WebRequest http://ligman.me/2u2KdXT -OutFile "Rapid Deployment Guide For Azure Rights Management.pdf"
Invoke-WebRequest http://ligman.me/1IW1s9S -OutFile "Rethinking Enterprise Storage A Hybrid Cloud Model.pdf"
Invoke-WebRequest http://ligman.me/2tEn8Zy -OutFile "BizTalk Server 2016 Licensing Datasheet.pdf"
Invoke-WebRequest http://ligman.me/2u0WD2F -OutFile "Enterprise Cloud Strategy.pdf"
Invoke-WebRequest http://ligman.me/2t2Ghm1 -OutFile "Enterprise Cloud Strategy - Mobile.pdf"
Invoke-WebRequest http://ligman.me/2sLiBTE -OutFile "dotNET Microservices Architecture for Containerized dotNET Applications.pdf"
Invoke-WebRequest http://ligman.me/1gfeQ27 -OutFile "dotNET Technology Guidance for Business Applications.pdf"
Invoke-WebRequest http://ligman.me/1KBM8DL -OutFile "Building Cloud Apps with Microsoft Azure Best practices for DevOps, data storage, high availability, and more.pdf"
Invoke-WebRequest http://ligman.me/2v7M0bp -OutFile "Containerized Docker Application Lifecycle with Microsoft Platform and Tools.pdf"
Invoke-WebRequest http://ligman.me/1dDcwQC -OutFile "Creating Mobile Apps with Xamarin.Forms, Preview Edition 2.pdf"
Invoke-WebRequest http://ligman.me/2u1190V -OutFile "Creating Mobile Apps with Xamarin.Forms Cross-platform C# programming for iOS, Android, and Windows.pdf"
Invoke-WebRequest http://ligman.me/1NErkvl -OutFile "Managing Agile Open-Source Software Projects with Microsoft Visual Studio Online.pdf"
Invoke-WebRequest http://ligman.me/1epZeHO -OutFile "Microsoft Azure Essentials Azure Web Apps for Developers.pdf"
Invoke-WebRequest http://ligman.me/2t2WqaR -OutFile "Microsoft Platform and Tools for Mobile App Development.pdf"
Invoke-WebRequest http://ligman.me/2sUA9kk -OutFile "Microsoft Platform and Tools for Mobile App Development - Mobile.pdf"
Invoke-WebRequest http://ligman.me/1CQXMEp -OutFile "Moving to Microsoft Visual Studio 2010.xps"
Invoke-WebRequest http://ligman.me/1JITgwM -OutFile "Moving to Microsoft Visual Studio 2010.pdf"
Invoke-WebRequest http://ligman.me/1LN5APL -OutFile "Programming Windows 8 Apps with HTML, CSS, and JavaScript.pdf"
Invoke-WebRequest http://ligman.me/1RWzfoe -OutFile "Programming Windows Store Apps with HTML, CSS, and JavaScript, Second Edition.pdf"
Invoke-WebRequest http://ligman.me/1LNdusd -OutFile "Programming Windows Phone 7 (Special Excerpt 2).xps"
Invoke-WebRequest http://ligman.me/1KyWLZv -OutFile "Programming Windows Phone 7 (Special Excerpt 2).pdf"
Invoke-WebRequest http://ligman.me/2tEKIoU -OutFile "Team Foundation Server to Visual Studio Team Services Migration Guide.pdf"
Invoke-WebRequest http://ligman.me/2uGZkV1 -OutFile "5 cool things you can do with CRM for tablets.pdf"
Invoke-WebRequest http://ligman.me/2tJAEuU -OutFile "Create Custom Analytics in Dynamics 365 with Power BI.pdf"
Invoke-WebRequest http://ligman.me/1odT1MW -OutFile "Create of Customize System Dashboards.pdf"
Invoke-WebRequest http://ligman.me/1NJ0vpb -OutFile "Create Your First CRM Marketing Campaign.pdf"
Invoke-WebRequest http://ligman.me/1dHBtdA -OutFile "CRM Basics for Outlook basics.pdf"
Invoke-WebRequest http://ligman.me/1NIYrxw -OutFile "CRM Basics for Sales Pros and Service Reps.pdf"
Invoke-WebRequest http://ligman.me/1qNYIYi -OutFile "Give Great Customer Service with CRM.pdf"
Invoke-WebRequest http://ligman.me/1rH9Ar3 -OutFile "Go Mobile with CRM for Phones - Express.pdf"
Invoke-WebRequest http://ligman.me/1kvWKEm -OutFile "Go Mobile with CRM for Tablets.pdf"
Invoke-WebRequest http://ligman.me/1m8yCMD -OutFile "Import Contacts into CRM.pdf"
Invoke-WebRequest http://ligman.me/1kvXrxj -OutFile "Introducing Microsoft Social Engagement.pdf"
Invoke-WebRequest http://ligman.me/1pUnYfG -OutFile "Introduction to Business Processes.pdf"
Invoke-WebRequest http://ligman.me/1CWgeLI -OutFile "Meet Your Service Goals with SLAs and Entitlements.pdf"
Invoke-WebRequest http://ligman.me/2v0ShWr -OutFile "Microsoft Dynamics CRM 2016 Interactive Service Hub User Guide.pdf"
Invoke-WebRequest http://ligman.me/2sF6M19 -OutFile "Microsoft Dynamics CRM 2016 On-Premises Volume Licensing and Pricing Guide.pdf"
Invoke-WebRequest http://ligman.me/2sVh6qf -OutFile "Microsoft Dynamics CRM for Outlook Installing Guide for use with Microsoft Dynamics CRM Online.pdf"
Invoke-WebRequest http://ligman.me/2tYdqU8 -OutFile "Microsoft Dynamics CRM Resource Guide 2015.pdf"
Invoke-WebRequest http://ligman.me/1oB9ptL -OutFile "Microsoft Social Engagement for CRM.pdf"
Invoke-WebRequest http://ligman.me/2sFbbl0 -OutFile "Product Overview and Capability Guide Microsoft Dynamics NAV 2016.pdf"
Invoke-WebRequest http://ligman.me/2v1ok8u -OutFile "RAP as a Service for Dynamics CRM.pdf"
Invoke-WebRequest http://ligman.me/1HIcIKB -OutFile "Set Up A Social Engagement Search For Your Product.pdf"
Invoke-WebRequest http://ligman.me/1Cl328D -OutFile "Social is for Closers.pdf"
Invoke-WebRequest http://ligman.me/VSpodw -OutFile "Start Working in CRM.pdf"
Invoke-WebRequest http://ligman.me/1S36CGa -OutFile "Your Brand Sux.pdf"
Invoke-WebRequest http://ligman.me/2tEPKBF -OutFile "10 essential tips and tools for mobile working.pdf"
Invoke-WebRequest http://ligman.me/2sVSiyp -OutFile "An employee’s guide to healthy computing.pdf"
Invoke-WebRequest http://ligman.me/1H1MFKr -OutFile "Introduction to Per Core Licensing and Basic Definitions.pdf"
Invoke-WebRequest http://ligman.me/2u2bSbh -OutFile "Licensing Windows and Microsoft Office for use on the Macintosh.pdf"
Invoke-WebRequest http://ligman.me/2u7XYoT -OutFile "VLSC Software Assurance Guide.pdf"
Invoke-WebRequest http://ligman.me/2txAWqi -OutFile "Windows Server 2016 and System Center 2016 Pricing and Licensing FAQs.pdf"
Invoke-WebRequest http://ligman.me/1sgBtn4 -OutFile "Access 2013 Keyboard Shortcuts.pdf"
Invoke-WebRequest http://ligman.me/2tEnvmU -OutFile "Azure AD-Office 365 seamless sign-in.pdf"
Invoke-WebRequest http://ligman.me/2txxLic -OutFile "Content Encryption in Microsoft Office 365.pdf"
Invoke-WebRequest http://ligman.me/2u89sJ3 -OutFile "Controlling Access to Office 365 and Protecting Content on Devices.pdf"
Invoke-WebRequest http://ligman.me/1qzON6Q -OutFile "Customize Word 2013 Keyboard Shortcuts.pdf"
Invoke-WebRequest http://ligman.me/2tXYR34 -OutFile "Data Resiliency in Microsoft Office 365.pdf"
Invoke-WebRequest http://ligman.me/1onTg9n -OutFile "Excel 2013 Keyboard Shortcuts.pdf"
Invoke-WebRequest http://ligman.me/VP2t2L -OutFile "Excel Online Keyboard Shortcuts.pdf"
Invoke-WebRequest http://ligman.me/2v0u0jd -OutFile "File Protection Solutions in Office 365.pdf"
Invoke-WebRequest http://ligman.me/1dD6v6s -OutFile "First Look Microsoft Office 2010.xps"
Invoke-WebRequest http://ligman.me/1Ra595J -OutFile "First Look Microsoft Office 2010.pdf"
Invoke-WebRequest http://ligman.me/2v0H3ku -OutFile "Get Started With Microsoft OneDrive.pdf"
Invoke-WebRequest http://ligman.me/2tEtms3 -OutFile "Get Started With Microsoft Project Online.pdf"
Invoke-WebRequest http://ligman.me/1jWMJA2 -OutFile "How To Recover That Un-Saved Office Document.pdf"
Invoke-WebRequest http://ligman.me/1qZlnOJ -OutFile "InfoPath 2013 Keyboard Shortcuts.pdf"
Invoke-WebRequest http://ligman.me/1xqtaWN -OutFile "Licensing Microsoft Office 365 ProPlus Subscription Service in Volume Licensing.pdf"
Invoke-WebRequest http://ligman.me/2v0v72p -OutFile "Licensing Microsoft Office software in Volume Licensing.pdf"
Invoke-WebRequest http://ligman.me/1HCDxl9 -OutFile "Microsoft Access 2013 Quick Start Guide.pdf"
Invoke-WebRequest http://ligman.me/2u7Lw8N -OutFile "Microsoft Classroom Deployment.pdf"
Invoke-WebRequest http://ligman.me/1HByNKS -OutFile "Microsoft Excel 2013 Quick Start Guide.pdf"
Invoke-WebRequest http://ligman.me/29a22WR -OutFile "Microsoft Excel 2016 for Mac Quick Start Guide.pdf"
Invoke-WebRequest http://ligman.me/29bcJtd -OutFile "Microsoft Excel 2016 Quick Start Guide.pdf"
Invoke-WebRequest http://ligman.me/29rwoHw -OutFile "Microsoft Excel Mobile Quick Start Guide.pdf"
Invoke-WebRequest http://ligman.me/2sF7s6H -OutFile "Microsoft Excel VLOOKUP Troubleshooting Tips.pdf"
Invoke-WebRequest http://ligman.me/1CSMobd -OutFile "Microsoft OneNote 2013 Quick Start Guide.pdf"
Invoke-WebRequest http://ligman.me/29d5XTw -OutFile "Microsoft OneNote 2016 for Mac Quick Start Guide.pdf"
Invoke-WebRequest http://ligman.me/29rwoY0 -OutFile "Microsoft OneNote 2016 Quick Start Guide.pdf"
Invoke-WebRequest http://ligman.me/29d1wc3 -OutFile "Microsoft OneNote 2016 Tips and Tricks.pdf"
Invoke-WebRequest http://ligman.me/29fudHc -OutFile "Microsoft OneNote Mobile Quick Start Guide.pdf"
Invoke-WebRequest http://ligman.me/1FYtDD8 -OutFile "Microsoft Outlook 2013 Quick Start Guide.pdf"
Invoke-WebRequest http://ligman.me/29hVdVa -OutFile "Microsoft Outlook 2016 for Mac Quick Start Guide.pdf"
Invoke-WebRequest http://ligman.me/29fDult -OutFile "Microsoft Outlook 2016 Quick Start Guide.pdf"
Invoke-WebRequest http://ligman.me/29cfePX -OutFile "Microsoft Outlook 2016 Tips and Tricks.pdf"
Invoke-WebRequest http://ligman.me/1NCfcKC -OutFile "Microsoft Powerpoint 2013 Quick Start Guide.pdf"
Invoke-WebRequest http://ligman.me/29fDylj -OutFile "Microsoft PowerPoint 2016 for Mac Quick Start Guide.pdf"
Invoke-WebRequest http://ligman.me/29fDylj -OutFile "Microsoft PowerPoint 2016 for Mac Quick Start Guide.pdf"
Invoke-WebRequest http://ligman.me/29d5AbX -OutFile "Microsoft PowerPoint Mobile Quick Start Guide.pdf"
Invoke-WebRequest http://ligman.me/1JI6V77 -OutFile "Microsoft Project 2013 Quick Start Guide.pdf"
Invoke-WebRequest http://ligman.me/1H4Q0e5 -OutFile "Microsoft Publisher 2013 Quick Start Guide.pdf"
Invoke-WebRequest http://ligman.me/1LMpRns -OutFile "Microsoft Visio 2013 Quick Start Guide.pdf"
Invoke-WebRequest http://ligman.me/1HCCCRP -OutFile "Microsoft Word 2013 Quick Start Guide.pdf"
Invoke-WebRequest http://ligman.me/29FzGG5 -OutFile "Microsoft Word 2016 for Mac Quick Start Guide.pdf"
Invoke-WebRequest http://ligman.me/29e6cTO -OutFile "Microsoft Word 2016 Quick Start Guide.pdf"
Invoke-WebRequest http://ligman.me/29gfrkN -OutFile "Microsoft Word Mobile Quick Start Guide.pdf"
Invoke-WebRequest http://ligman.me/1Ra5c1c -OutFile "Microsoft Office 365 Connect and Collaborate Virtually Anywhere, Anytime.pdf"
Invoke-WebRequest http://ligman.me/2sVGUSX -OutFile "Office 365 Dedicated Platform vNext Service Release.pdf"
Invoke-WebRequest http://ligman.me/2u1KmL9 -OutFile "Office 365 Licensing Brief.pdf"
Invoke-WebRequest http://ligman.me/1n49kzj -OutFile "OneNote 2013 Keyboard Shortcuts.pdf"
Invoke-WebRequest http://ligman.me/1qZlFVR -OutFile "OneNote Online Keyboard Shortcuts.pdf"
Invoke-WebRequest http://ligman.me/TWa2Dg -OutFile "Outlook 2013 Keyboard Shortcuts.pdf"
Invoke-WebRequest http://ligman.me/1xzdEtT -OutFile "Outlook Web App Keyboard Shortcuts.pdf"
Invoke-WebRequest http://ligman.me/1HCQyeA -OutFile "Own Your Future Update Your Skills with Resources and Career Ideas from Microsoft.xps"
Invoke-WebRequest http://ligman.me/1Cg5iOv -OutFile "Own Your Future Update Your Skills with Resources and Career Ideas from Microsoft.pdf"
Invoke-WebRequest http://ligman.me/1onU8Ld -OutFile "PowerPoint Online Keyboard Shortcuts.pdf"
Invoke-WebRequest http://ligman.me/1vM9mwt -OutFile "Project 2013 Keyboard Shortcuts.pdf"
Invoke-WebRequest http://ligman.me/1rB8nl1 -OutFile "Publisher 2013 Keyboard Shortcuts.pdf"
Invoke-WebRequest http://ligman.me/1JDjqUt -OutFile "Security and Privacy For Microsoft Office 2010 Users.pdf"
Invoke-WebRequest http://ligman.me/2tYk9gX -OutFile "Security Incident Management in Microsoft Office 365.pdf"
Invoke-WebRequest http://ligman.me/2tYk9gX -OutFile "Security Incident Management in Microsoft Office 365.pdf"
Invoke-WebRequest http://ligman.me/2sVrsGy -OutFile "SharePoint Online Dedicated & OneDrive for Business Dedicated vNext Service Release.pdf"
Invoke-WebRequest http://ligman.me/1M7Xr5v -OutFile "Skype for Business User Tips & Tricks for Anyone.pdf"
Invoke-WebRequest http://ligman.me/2t3nqXV -OutFile "Switching from Google Apps to Office 365 for business.pdf"
Invoke-WebRequest http://ligman.me/2u2K9aI -OutFile "Tenant Isolation in Microsoft Office 365.pdf"
Invoke-WebRequest http://ligman.me/1vM9H2d -OutFile "Visio 2013 Keyboard Shortcuts.pdf"
Invoke-WebRequest http://ligman.me/2sFsnXy -OutFile "Windows 10 Tips and Tricks.pdf"
Invoke-WebRequest http://ligman.me/1m6xucg -OutFile "Word 2013 Keyboard Shortcuts.pdf"
Invoke-WebRequest http://ligman.me/1qzRntH -OutFile "Word Online Keyboard Shortcuts.pdf"
Invoke-WebRequest http://ligman.me/1lJmKeW -OutFile "Working with SmartArt Graphics Keyboard Shortcuts.pdf"
Invoke-WebRequest http://ligman.me/2t3HOIt -OutFile "How to plan capacity for embedded analytics with Power BI Premium.pdf"
Invoke-WebRequest http://ligman.me/2tE789y -OutFile "Introducing Microsoft Power BI.pdf"
Invoke-WebRequest http://ligman.me/2sUDY9j -OutFile "Introducing Microsoft Power BI - Mobile.pdf"
Invoke-WebRequest http://ligman.me/2tEI5U4 -OutFile "Microsoft Power BI Premium Whitepaper.pdf"
Invoke-WebRequest http://ligman.me/2uH1kN1 -OutFile "Microsoft Dynamics GP 2015 R2 PowerShell Users Guide.pdf"
Invoke-WebRequest http://ligman.me/2tY8L4x -OutFile "PowerShell Integrated Scripting Environment 3.0.pdf"
Invoke-WebRequest http://ligman.me/2tyf2TJ -OutFile "Simplify Group Policy administration with Windows PowerShell.pdf"
Invoke-WebRequest http://ligman.me/2v0CY01 -OutFile "Windows PowerShell - Management of Active Directory Infrastructure.pdf"
Invoke-WebRequest http://ligman.me/2v0vXMn -OutFile "Windows PowerShell 3.0 Examples.pdf"
Invoke-WebRequest http://ligman.me/2u8l13d -OutFile "Windows PowerShell 3.0 Language Quick Reference.pdf"
Invoke-WebRequest http://ligman.me/2u8jZEr -OutFile "WINDOWS POWERSHELL 4.0 LANGUAGE QUICK REFERENCE.pdf"
Invoke-WebRequest http://ligman.me/1omCrM6 -OutFile "Windows PowerShell 4.0 Language Reference Examples.pdf"
Invoke-WebRequest http://ligman.me/2sFvbUs -OutFile "Windows PowerShell Command Builder User’s Guide.pdf"
Invoke-WebRequest http://ligman.me/2tYmSHb -OutFile "Windows PowerShell Desired State Configuration Quick Reference.pdf"
Invoke-WebRequest http://ligman.me/1n3mkVY -OutFile "WINDOWS POWERSHELL INTEGRATED SCRIPTING ENVIRONMENT 4.0.pdf"
Invoke-WebRequest http://ligman.me/2tEXUKw -OutFile "Windows PowerShell Web Access.pdf"
Invoke-WebRequest http://ligman.me/2tEAt3Z -OutFile "WMI in PowerShell 3.0.pdf"
Invoke-WebRequest http://ligman.me/2t3uPGw -OutFile "WMI in Windows PowerShell 4.0.pdf"
Invoke-WebRequest http://ligman.me/2uFTByu -OutFile "Configuring Microsoft SharePoint Hybrid Capabilities.pdf"
Invoke-WebRequest http://ligman.me/2tXvePt -OutFile "Configuring Microsoft SharePoint Hybrid Capabilities - Mobile.pdf"
Invoke-WebRequest http://ligman.me/12FIZ1I -OutFile "Deployment guide for Microsoft SharePoint 2013.pdf"
Invoke-WebRequest http://ligman.me/2v0Dhb1 -OutFile "Microsoft SharePoint Server 2016 Architectural Models.pdf"
Invoke-WebRequest http://ligman.me/2u0QCD2 -OutFile "Planning and Preparing for Microsoft SharePoint Hybrid - 8.5 X 11.pdf"
Invoke-WebRequest http://ligman.me/2sEzMGA -OutFile "Planning and Preparing for Microsoft SharePoint Hybrid - Mobile.pdf"
Invoke-WebRequest http://ligman.me/2u8h5PG -OutFile "RAP as a Service for SharePoint Server.pdf"
Invoke-WebRequest http://ligman.me/2uGN9ao -OutFile "SharePoint Online Dedicated Service Description.pdf"
Invoke-WebRequest http://ligman.me/TL3pn1 -OutFile "SharePoint Products Keyboard Shortcuts.pdf"
Invoke-WebRequest http://ligman.me/2txHeGo -OutFile "SharePoint Server 2016 Databases - Quick Reference Guide.pdf"
Invoke-WebRequest http://ligman.me/29FkNr3 -OutFile "SharePoint Server 2016 Quick Start Guide.pdf"
Invoke-WebRequest http://ligman.me/1anyEJj -OutFile "5 Tips For A Smooth SSIS Upgrade to SQL Server 2012.pdf"
Invoke-WebRequest http://ligman.me/N1HEpM -OutFile "Backup and Restore of SQL Server Databases.pdf"
Invoke-WebRequest http://ligman.me/2sVpUwk -OutFile "Data Science with Microsoft SQL Server 2016.pdf"
Invoke-WebRequest http://ligman.me/2u8ao0i -OutFile "Deeper insights across data with SQL Server 2016 - Technical White Paper.pdf"
Invoke-WebRequest http://ligman.me/1ReR3Qq -OutFile "Guide to Migrating from Oracle to SQL Server 2014 and Azure SQL Database.pdf"
Invoke-WebRequest http://ligman.me/1RWzIGZ -OutFile "Introducing Microsoft Azure HDInsight.pdf"
Invoke-WebRequest http://ligman.me/2u2j5sf -OutFile "Introducing Microsoft Data Warehouse Fast Track for SQL Server 2016.pdf"
Invoke-WebRequest http://ligman.me/1gfab07 -OutFile "Introducing Microsoft SQL Server 2012.pdf"
Invoke-WebRequest http://ligman.me/1C7dU9J -OutFile "Introducing Microsoft SQL Server 2014.pdf"
Invoke-WebRequest http://ligman.me/2u7ml6r -OutFile "Introducing Microsoft SQL Server 2016 Mission-Critical Applications, Deeper Insights, Hyperscale Cloud, Preview 2.pdf"
Invoke-WebRequest http://ligman.me/2t2o340 -OutFile "Introducing Microsoft SQL Server 2016 Mission-Critical Applications, Deeper Insights, Hyperscale Cloud, Preview 2 - Mobile.pdf"
Invoke-WebRequest http://ligman.me/1CQXzko -OutFile "Introducing Microsoft SQL Server 2008 R2.xps"
Invoke-WebRequest http://ligman.me/1KyNJvs -OutFile "Introducing Microsoft SQL Server 2008 R2.pdf"
Invoke-WebRequest http://ligman.me/29pcQFA -OutFile "Microsoft SharePoint Server 2016 Reviewer’s Guide.pdf"
Invoke-WebRequest http://ligman.me/N1J8A8 -OutFile "Microsoft SQL Server 2012 Tutorials Analysis Services - Data Mining Step-by-Step.pdf"
Invoke-WebRequest http://ligman.me/N1JfvI -OutFile "Microsoft SQL Server 2012 Tutorials Analysis Services - Multidimensional Modeling Step-by-Step.pdf"
Invoke-WebRequest http://ligman.me/16E6G9L -OutFile "Microsoft SQL Server 2012 Tutorials Reporting Services Quick Step-by-Step.pdf"
Invoke-WebRequest http://ligman.me/16dHXZ9 -OutFile "Microsoft SQL Server 2012 Tutorials Writing Transact-SQL-Statements.pdf"
Invoke-WebRequest http://ligman.me/1S1f34H -OutFile "Microsoft SQL Server 2014 Licensing Guide.pdf"
Invoke-WebRequest http://ligman.me/2sFqolM -OutFile "Microsoft SQL Server 2016 Licensing Datasheet.pdf"
Invoke-WebRequest http://ligman.me/2tEHwtq -OutFile "Microsoft SQL Server 2016 Licensing Guide.pdf"
Invoke-WebRequest http://ligman.me/2uGQTc7 -OutFile "Microsoft SQL Server 2016 Mission-Critical Performance Technical White Paper.pdf"
Invoke-WebRequest http://ligman.me/2u7TbUy -OutFile "Microsoft SQL Server 2016 New Innovations.pdf"
Invoke-WebRequest http://ligman.me/2tYmEzR -OutFile "Microsoft SQL Server 2016 SP1 Editions.pdf"
Invoke-WebRequest http://ligman.me/2tYaW8d -OutFile "Microsoft SQL Server In-Memory OLTP and Columnstore Feature Comparison.pdf"
Invoke-WebRequest http://ligman.me/2u2HKg6 -OutFile "RAP as a Service for SQL Server.pdf"
Invoke-WebRequest http://ligman.me/2tEHLVm -OutFile "SQLCAT’s Guide to Relational Engine.pdf"
Invoke-WebRequest http://ligman.me/11IMDlh -OutFile "Xquery Language Reference.pdf"
Invoke-WebRequest http://ligman.me/29i2CEe -OutFile "Surface Book User Guide.pdf"
Invoke-WebRequest http://ligman.me/29hofVk -OutFile "Surface Pro 4 User Guide.pdf"
Invoke-WebRequest http://ligman.me/1dD6S0J -OutFile "Introducing Microsoft System Center 2012 R2.pdf"
Invoke-WebRequest http://ligman.me/2sUch05 -OutFile "Microsoft System Center Building a Virtualized Network Solution, Second Edition.pdf"
Invoke-WebRequest http://ligman.me/1JDrhBp -OutFile "Microsoft System Center Data Protection for the Hybrid Cloud.pdf"
Invoke-WebRequest http://ligman.me/1C7okGv -OutFile "Microsoft System Center Deploying Hyper-V with Software-Defined Storage & Networking.pdf"
Invoke-WebRequest http://ligman.me/1KBVfnS -OutFile "Microsoft System Center Extending Operations Manager Reporting.pdf"
Invoke-WebRequest http://ligman.me/1IzHZA1 -OutFile "Microsoft System Center Introduction to Microsoft Automation Solutions.pdf"
Invoke-WebRequest http://ligman.me/1GUUqSD -OutFile "Microsoft System Center Operations Manager Field Experience.pdf"
Invoke-WebRequest http://ligman.me/1CQXNbj -OutFile "Microsoft System Center Software Update Management Field Experience.pdf"
Invoke-WebRequest http://ligman.me/1GUOZ6b -OutFile "Microsoft System Center Building a Virtualized Network Solution.pdf"
Invoke-WebRequest http://ligman.me/1GUP0qL -OutFile "Microsoft System Center Cloud Management with App Controller.pdf"
Invoke-WebRequest http://ligman.me/1KBMN8a -OutFile "Microsoft System Center Configuration Manager Field Experience.pdf"
Invoke-WebRequest http://ligman.me/1f9cKQZ -OutFile "Microsoft System Center Designing Orchestrator Runbooks.pdf"
Invoke-WebRequest http://ligman.me/1gfaIzh -OutFile "Microsoft System Center Integrated Cloud Platform.pdf"
Invoke-WebRequest http://ligman.me/1JIF6vB -OutFile "Microsoft System Center Network Virtualization and Cloud Computing.pdf"
Invoke-WebRequest http://ligman.me/1M00Lzu -OutFile "Microsoft System Center Optimizing Service Manager.pdf"
Invoke-WebRequest http://ligman.me/1M00v3u -OutFile "Microsoft System Center Troubleshooting Configuration Manager.pdf"
Invoke-WebRequest http://ligman.me/2t3NaDl -OutFile "What’s new in System Center 2016 White Paper.pdf"
Invoke-WebRequest http://ligman.me/1M05yAY -OutFile "Understanding Microsoft Virtualizaton R2 Solutions.xps"
Invoke-WebRequest http://ligman.me/1eql6Ts -OutFile "Understanding Microsoft Virtualizaton R2 Solutions.pdf"
Invoke-WebRequest http://ligman.me/2sE9XX1 -OutFile "Deploying Windows 10 Automating deployment by using System Center Configuration Manager.pdf"
Invoke-WebRequest http://ligman.me/2twLeqF -OutFile "Deploying Windows 10 Automating deployment by using System Center Configuration Manager - Mobile.pdf"
Invoke-WebRequest http://ligman.me/2t2WmYx -OutFile "Introducing Windows 10 for IT Professionals.pdf"
Invoke-WebRequest http://ligman.me/1Uiyx8Q -OutFile "Introducing Windows 10 for IT Professionals, Preview Edition.pdf"
Invoke-WebRequest http://ligman.me/1JDrMeG -OutFile "Introducing Windows 8.1 for IT Professionals.pdf"
Invoke-WebRequest http://ligman.me/1GVGQgI -OutFile "Introducing Windows 8 An Overview for IT Professionals.pdf"
Invoke-WebRequest http://ligman.me/2txIfxW -OutFile "Licensing Windows desktop operating system for use with virtual machines.pdf"
Invoke-WebRequest http://ligman.me/2u2R83b -OutFile "RAP as a Service for Windows Desktop.pdf"
Invoke-WebRequest http://ligman.me/2sFzkaR -OutFile "Volume Licensing Reference Guide Windows 10 Desktop Operating System.pdf"
Invoke-WebRequest http://ligman.me/2u12Nj7 -OutFile "Windows 10 IT Pro Essentials Support Secrets.pdf"
Invoke-WebRequest http://ligman.me/2uFUOG1 -OutFile "Windows 10 IT Pro Essentials Support Secrets.pdf"
Invoke-WebRequest http://ligman.me/2t2cYjp -OutFile "Windows 10 IT Pro Essentials Top 10 Tools.pdf"
Invoke-WebRequest http://ligman.me/2u15CAR -OutFile "Windows 10 IT Pro Essentials Top 10 Tools - Mobile.pdf"
Invoke-WebRequest http://ligman.me/1sfkqBW -OutFile "Work Smart Windows 8 Shortcut Keys.pdf"
Invoke-WebRequest http://ligman.me/1M06aXa -OutFile "Introducing Windows Server 2008 R2.xps"
Invoke-WebRequest http://ligman.me/1FYVYcy -OutFile "Introducing Windows Server 2008 R2.pdf"
Invoke-WebRequest http://ligman.me/1M0681D -OutFile "Introducing Windows Server 2012.pdf"
Invoke-WebRequest http://ligman.me/1NCxHi5 -OutFile "Introducing Windows Server 2012 R2.pdf"
Invoke-WebRequest http://ligman.me/2uFKRZd -OutFile "Introducing Windows Server 2016.pdf"
Invoke-WebRequest http://ligman.me/2tDMJl0 -OutFile "Introducing Windows Server 2016 - Mobile.pdf"
Invoke-WebRequest http://ligman.me/2uFDelL -OutFile "Introducing Windows Server 2016 Technical Preview.pdf"
Invoke-WebRequest http://ligman.me/2twmtKY -OutFile "Introducing Windows Server 2016 Technical Preview - Mobile.pdf"
Invoke-WebRequest http://ligman.me/1f9k8fe -OutFile "Introducing Windows Server 2012 R2 Preview Release.pdf"
Invoke-WebRequest http://ligman.me/2v1cDyG -OutFile "Offline Assessment for Active Directory.pdf"
Invoke-WebRequest http://ligman.me/2txRQFd -OutFile "RAP as a Service for Active Directory.pdf"
Invoke-WebRequest http://ligman.me/2v1zdYa -OutFile "RAP as a Service for Failover Cluster.pdf"
Invoke-WebRequest http://ligman.me/2sW0A9v -OutFile "RAP as a Service for Internet Information Services.pdf"
Invoke-WebRequest http://ligman.me/2txQLgl -OutFile "RAP as a Service for Windows Server Hyper-V.pdf"
Invoke-WebRequest http://ligman.me/2sFbVq3 -OutFile "Windows Server 2016 Licensing.pdf"
