Invoke-WebRequest http://ligman.me/1IW1oab | Out-File -Append -NoClobber "Introducing Windows Azure for IT Professionals.pdf"
Invoke-WebRequest http://ligman.me/1H4VXHT | Out-File -Append -NoClobber "Microsoft Azure Essentials Azure Automation.pdf"
Invoke-WebRequest http://ligman.me/1NDTZR4 | Out-File -Append -NoClobber "Microsoft Azure Essentials Azure Machine Learning.pdf"
Invoke-WebRequest http://ligman.me/1JIhgjA | Out-File -Append -NoClobber "Microsoft Azure Essentials Fundamentals of Azure.pdf"
Invoke-WebRequest http://ligman.me/2sUanwC | Out-File -Append -NoClobber "Microsoft Azure Essentials Fundamentals of Azure, Second Edition.pdf"
Invoke-WebRequest http://ligman.me/2twPBSD | Out-File -Append -NoClobber "Microsoft Azure Essentials Fundamentals of Azure, Second Edition Mobile.pdf"
Invoke-WebRequest http://ligman.me/2tE7q0i | Out-File -Append -NoClobber "Microsoft Azure Essentials Migrating SQL Server Databases to Azure - Mobile.pdf"
Invoke-WebRequest http://ligman.me/2t2y29a | Out-File -Append -NoClobber "Microsoft Azure Essentials Migrating SQL Server Databases to Azure 8.5X11.pdf"
Invoke-WebRequest http://ligman.me/2tJ1pj4 | Out-File -Append -NoClobber "Microsoft Azure ExpressRoute Guide.pdf"
Invoke-WebRequest http://ligman.me/2u2KdXT | Out-File -Append -NoClobber "Rapid Deployment Guide For Azure Rights Management.pdf"
Invoke-WebRequest http://ligman.me/1IW1s9S | Out-File -Append -NoClobber "Rethinking Enterprise Storage A Hybrid Cloud Model.pdf"
Invoke-WebRequest http://ligman.me/2tEn8Zy | Out-File -Append -NoClobber "BizTalk Server 2016 Licensing Datasheet.pdf"
Invoke-WebRequest http://ligman.me/2u0WD2F | Out-File -Append -NoClobber "Enterprise Cloud Strategy.pdf"
Invoke-WebRequest http://ligman.me/2t2Ghm1 | Out-File -Append -NoClobber "Enterprise Cloud Strategy - Mobile.pdf"
Invoke-WebRequest http://ligman.me/2sLiBTE | Out-File -Append -NoClobber "dotNET Microservices Architecture for Containerized dotNET Applications.pdf"
Invoke-WebRequest http://ligman.me/1gfeQ27 | Out-File -Append -NoClobber "dotNET Technology Guidance for Business Applications.pdf"
Invoke-WebRequest http://ligman.me/1KBM8DL | Out-File -Append -NoClobber "Building Cloud Apps with Microsoft Azure Best practices for DevOps, data storage, high availability, and more.pdf"
Invoke-WebRequest http://ligman.me/2v7M0bp | Out-File -Append -NoClobber "Containerized Docker Application Lifecycle with Microsoft Platform and Tools.pdf"
Invoke-WebRequest http://ligman.me/1dDcwQC | Out-File -Append -NoClobber "Creating Mobile Apps with Xamarin.Forms, Preview Edition 2.pdf"
Invoke-WebRequest http://ligman.me/2u1190V | Out-File -Append -NoClobber "Creating Mobile Apps with Xamarin.Forms Cross-platform C# programming for iOS, Android, and Windows.pdf"
Invoke-WebRequest http://ligman.me/1NErkvl | Out-File -Append -NoClobber "Managing Agile Open-Source Software Projects with Microsoft Visual Studio Online.pdf"
Invoke-WebRequest http://ligman.me/1epZeHO | Out-File -Append -NoClobber "Microsoft Azure Essentials Azure Web Apps for Developers.pdf"
Invoke-WebRequest http://ligman.me/2t2WqaR | Out-File -Append -NoClobber "Microsoft Platform and Tools for Mobile App Development.pdf"
Invoke-WebRequest http://ligman.me/2sUA9kk | Out-File -Append -NoClobber "Microsoft Platform and Tools for Mobile App Development - Mobile.pdf"
Invoke-WebRequest http://ligman.me/1JITgwM | Out-File -Append -NoClobber "Moving to Microsoft Visual Studio 2010.pdf"
Invoke-WebRequest http://ligman.me/1LN5APL | Out-File -Append -NoClobber "Programming Windows 8 Apps with HTML, CSS, and JavaScript.pdf"
Invoke-WebRequest http://ligman.me/1RWzfoe | Out-File -Append -NoClobber "Programming Windows Store Apps with HTML, CSS, and JavaScript, Second Edition.pdf"
Invoke-WebRequest http://ligman.me/1KyWLZv | Out-File -Append -NoClobber "Programming Windows Phone 7 (Special Excerpt 2).pdf"
Invoke-WebRequest http://ligman.me/2tEKIoU | Out-File -Append -NoClobber "Team Foundation Server to Visual Studio Team Services Migration Guide.pdf"
Invoke-WebRequest http://ligman.me/2uGZkV1 | Out-File -Append -NoClobber "5 cool things you can do with CRM for tablets.pdf"
Invoke-WebRequest http://ligman.me/2tJAEuU | Out-File -Append -NoClobber "Create Custom Analytics in Dynamics 365 with Power BI.pdf"
Invoke-WebRequest http://ligman.me/1odT1MW | Out-File -Append -NoClobber "Create of Customize System Dashboards.pdf"
Invoke-WebRequest http://ligman.me/1NJ0vpb | Out-File -Append -NoClobber "Create Your First CRM Marketing Campaign.pdf"
Invoke-WebRequest http://ligman.me/1dHBtdA | Out-File -Append -NoClobber "CRM Basics for Outlook basics.pdf"
Invoke-WebRequest http://ligman.me/1NIYrxw | Out-File -Append -NoClobber "CRM Basics for Sales Pros and Service Reps.pdf"
Invoke-WebRequest http://ligman.me/1qNYIYi | Out-File -Append -NoClobber "Give Great Customer Service with CRM.pdf"
Invoke-WebRequest http://ligman.me/1rH9Ar3 | Out-File -Append -NoClobber "Go Mobile with CRM for Phones - Express.pdf"
Invoke-WebRequest http://ligman.me/1kvWKEm | Out-File -Append -NoClobber "Go Mobile with CRM for Tablets.pdf"
Invoke-WebRequest http://ligman.me/1m8yCMD | Out-File -Append -NoClobber "Import Contacts into CRM.pdf"
Invoke-WebRequest http://ligman.me/1kvXrxj | Out-File -Append -NoClobber "Introducing Microsoft Social Engagement.pdf"
Invoke-WebRequest http://ligman.me/1pUnYfG | Out-File -Append -NoClobber "Introduction to Business Processes.pdf"
Invoke-WebRequest http://ligman.me/1CWgeLI | Out-File -Append -NoClobber "Meet Your Service Goals with SLAs and Entitlements.pdf"
Invoke-WebRequest http://ligman.me/2v0ShWr | Out-File -Append -NoClobber "Microsoft Dynamics CRM 2016 Interactive Service Hub User Guide.pdf"
Invoke-WebRequest http://ligman.me/2sF6M19 | Out-File -Append -NoClobber "Microsoft Dynamics CRM 2016 On-Premises Volume Licensing and Pricing Guide.pdf"
Invoke-WebRequest http://ligman.me/2sVh6qf | Out-File -Append -NoClobber "Microsoft Dynamics CRM for Outlook Installing Guide for use with Microsoft Dynamics CRM Online.pdf"
Invoke-WebRequest http://ligman.me/2tYdqU8 | Out-File -Append -NoClobber "Microsoft Dynamics CRM Resource Guide 2015.pdf"
Invoke-WebRequest http://ligman.me/1oB9ptL | Out-File -Append -NoClobber "Microsoft Social Engagement for CRM.pdf"
Invoke-WebRequest http://ligman.me/2sFbbl0 | Out-File -Append -NoClobber "Product Overview and Capability Guide Microsoft Dynamics NAV 2016.pdf"
Invoke-WebRequest http://ligman.me/2v1ok8u | Out-File -Append -NoClobber "RAP as a Service for Dynamics CRM.pdf"
Invoke-WebRequest http://ligman.me/1HIcIKB | Out-File -Append -NoClobber "Set Up A Social Engagement Search For Your Product.pdf"
Invoke-WebRequest http://ligman.me/1Cl328D | Out-File -Append -NoClobber "Social is for Closers.pdf"
Invoke-WebRequest http://ligman.me/VSpodw | Out-File -Append -NoClobber "Start Working in CRM.pdf"
Invoke-WebRequest http://ligman.me/1S36CGa | Out-File -Append -NoClobber "Your Brand Sux.pdf"
Invoke-WebRequest http://ligman.me/2tEPKBF | Out-File -Append -NoClobber "10 essential tips and tools for mobile working.pdf"
Invoke-WebRequest http://ligman.me/2sVSiyp | Out-File -Append -NoClobber "An employee's guide to healthy computing.pdf"
Invoke-WebRequest http://ligman.me/1H1MFKr | Out-File -Append -NoClobber "Introduction to Per Core Licensing and Basic Definitions.pdf"
Invoke-WebRequest http://ligman.me/2u2bSbh | Out-File -Append -NoClobber "Licensing Windows and Microsoft Office for use on the Macintosh.pdf"
Invoke-WebRequest http://ligman.me/2u7XYoT | Out-File -Append -NoClobber "VLSC Software Assurance Guide.pdf"
Invoke-WebRequest http://ligman.me/2txAWqi | Out-File -Append -NoClobber "Windows Server 2016 and System Center 2016 Pricing and Licensing FAQs.pdf"
Invoke-WebRequest http://ligman.me/1sgBtn4 | Out-File -Append -NoClobber "Access 2013 Keyboard Shortcuts.pdf"
Invoke-WebRequest http://ligman.me/2tEnvmU | Out-File -Append -NoClobber "Azure AD-Office 365 seamless sign-in.pdf"
Invoke-WebRequest http://ligman.me/2txxLic | Out-File -Append -NoClobber "Content Encryption in Microsoft Office 365.pdf"
Invoke-WebRequest http://ligman.me/2u89sJ3 | Out-File -Append -NoClobber "Controlling Access to Office 365 and Protecting Content on Devices.pdf"
Invoke-WebRequest http://ligman.me/1qzON6Q | Out-File -Append -NoClobber "Customize Word 2013 Keyboard Shortcuts.pdf"
Invoke-WebRequest http://ligman.me/2tXYR34 | Out-File -Append -NoClobber "Data Resiliency in Microsoft Office 365.pdf"
Invoke-WebRequest http://ligman.me/1onTg9n | Out-File -Append -NoClobber "Excel 2013 Keyboard Shortcuts.pdf"
Invoke-WebRequest http://ligman.me/VP2t2L | Out-File -Append -NoClobber "Excel Online Keyboard Shortcuts.pdf"
Invoke-WebRequest http://ligman.me/2v0u0jd | Out-File -Append -NoClobber "File Protection Solutions in Office 365.pdf"
Invoke-WebRequest http://ligman.me/1Ra595J | Out-File -Append -NoClobber "First Look Microsoft Office 2010.pdf"
Invoke-WebRequest http://ligman.me/2v0H3ku | Out-File -Append -NoClobber "Get Started With Microsoft OneDrive.pdf"
Invoke-WebRequest http://ligman.me/2tEtms3 | Out-File -Append -NoClobber "Get Started With Microsoft Project Online.pdf"
Invoke-WebRequest http://ligman.me/1jWMJA2 | Out-File -Append -NoClobber "How To Recover That Un-Saved Office Document.pdf"
Invoke-WebRequest http://ligman.me/1qZlnOJ | Out-File -Append -NoClobber "InfoPath 2013 Keyboard Shortcuts.pdf"
Invoke-WebRequest http://ligman.me/1xqtaWN | Out-File -Append -NoClobber "Licensing Microsoft Office 365 ProPlus Subscription Service in Volume Licensing.pdf"
Invoke-WebRequest http://ligman.me/2v0v72p | Out-File -Append -NoClobber "Licensing Microsoft Office software in Volume Licensing.pdf"
Invoke-WebRequest http://ligman.me/1HCDxl9 | Out-File -Append -NoClobber "Microsoft Access 2013 Quick Start Guide.pdf"
Invoke-WebRequest http://ligman.me/2u7Lw8N | Out-File -Append -NoClobber "Microsoft Classroom Deployment.pdf"
Invoke-WebRequest http://ligman.me/1HByNKS | Out-File -Append -NoClobber "Microsoft Excel 2013 Quick Start Guide.pdf"
Invoke-WebRequest http://ligman.me/29a22WR | Out-File -Append -NoClobber "Microsoft Excel 2016 for Mac Quick Start Guide.pdf"
Invoke-WebRequest http://ligman.me/29bcJtd | Out-File -Append -NoClobber "Microsoft Excel 2016 Quick Start Guide.pdf"
Invoke-WebRequest http://ligman.me/29rwoHw | Out-File -Append -NoClobber "Microsoft Excel Mobile Quick Start Guide.pdf"
Invoke-WebRequest http://ligman.me/2sF7s6H | Out-File -Append -NoClobber "Microsoft Excel VLOOKUP Troubleshooting Tips.pdf"
Invoke-WebRequest http://ligman.me/1CSMobd | Out-File -Append -NoClobber "Microsoft OneNote 2013 Quick Start Guide.pdf"
Invoke-WebRequest http://ligman.me/29d5XTw | Out-File -Append -NoClobber "Microsoft OneNote 2016 for Mac Quick Start Guide.pdf"
Invoke-WebRequest http://ligman.me/29rwoY0 | Out-File -Append -NoClobber "Microsoft OneNote 2016 Quick Start Guide.pdf"
Invoke-WebRequest http://ligman.me/29d1wc3 | Out-File -Append -NoClobber "Microsoft OneNote 2016 Tips and Tricks.pdf"
Invoke-WebRequest http://ligman.me/29fudHc | Out-File -Append -NoClobber "Microsoft OneNote Mobile Quick Start Guide.pdf"
Invoke-WebRequest http://ligman.me/1FYtDD8 | Out-File -Append -NoClobber "Microsoft Outlook 2013 Quick Start Guide.pdf"
Invoke-WebRequest http://ligman.me/29hVdVa | Out-File -Append -NoClobber "Microsoft Outlook 2016 for Mac Quick Start Guide.pdf"
Invoke-WebRequest http://ligman.me/29fDult | Out-File -Append -NoClobber "Microsoft Outlook 2016 Quick Start Guide.pdf"
Invoke-WebRequest http://ligman.me/29cfePX | Out-File -Append -NoClobber "Microsoft Outlook 2016 Tips and Tricks.pdf"
Invoke-WebRequest http://ligman.me/1NCfcKC | Out-File -Append -NoClobber "Microsoft Powerpoint 2013 Quick Start Guide.pdf"
Invoke-WebRequest http://ligman.me/29fDylj | Out-File -Append -NoClobber "Microsoft PowerPoint 2016 for Mac Quick Start Guide.pdf"
Invoke-WebRequest http://ligman.me/29fDylj | Out-File -Append -NoClobber "Microsoft PowerPoint 2016 for Mac Quick Start Guide.pdf"
Invoke-WebRequest http://ligman.me/29d5AbX | Out-File -Append -NoClobber "Microsoft PowerPoint Mobile Quick Start Guide.pdf"
Invoke-WebRequest http://ligman.me/1JI6V77 | Out-File -Append -NoClobber "Microsoft Project 2013 Quick Start Guide.pdf"
Invoke-WebRequest http://ligman.me/1H4Q0e5 | Out-File -Append -NoClobber "Microsoft Publisher 2013 Quick Start Guide.pdf"
Invoke-WebRequest http://ligman.me/1LMpRns | Out-File -Append -NoClobber "Microsoft Visio 2013 Quick Start Guide.pdf"
Invoke-WebRequest http://ligman.me/1HCCCRP | Out-File -Append -NoClobber "Microsoft Word 2013 Quick Start Guide.pdf"
Invoke-WebRequest http://ligman.me/29FzGG5 | Out-File -Append -NoClobber "Microsoft Word 2016 for Mac Quick Start Guide.pdf"
Invoke-WebRequest http://ligman.me/29e6cTO | Out-File -Append -NoClobber "Microsoft Word 2016 Quick Start Guide.pdf"
Invoke-WebRequest http://ligman.me/29gfrkN | Out-File -Append -NoClobber "Microsoft Word Mobile Quick Start Guide.pdf"
Invoke-WebRequest http://ligman.me/1Ra5c1c | Out-File -Append -NoClobber "Microsoft Office 365 Connect and Collaborate Virtually Anywhere, Anytime.pdf"
Invoke-WebRequest http://ligman.me/2sVGUSX | Out-File -Append -NoClobber "Office 365 Dedicated Platform vNext Service Release.pdf"
Invoke-WebRequest http://ligman.me/2u1KmL9 | Out-File -Append -NoClobber "Office 365 Licensing Brief.pdf"
Invoke-WebRequest http://ligman.me/1n49kzj | Out-File -Append -NoClobber "OneNote 2013 Keyboard Shortcuts.pdf"
Invoke-WebRequest http://ligman.me/1qZlFVR | Out-File -Append -NoClobber "OneNote Online Keyboard Shortcuts.pdf"
Invoke-WebRequest http://ligman.me/TWa2Dg | Out-File -Append -NoClobber "Outlook 2013 Keyboard Shortcuts.pdf"
Invoke-WebRequest http://ligman.me/1xzdEtT | Out-File -Append -NoClobber "Outlook Web App Keyboard Shortcuts.pdf"
Invoke-WebRequest http://ligman.me/1Cg5iOv | Out-File -Append -NoClobber "Own Your Future Update Your Skills with Resources and Career Ideas from Microsoft.pdf"
Invoke-WebRequest http://ligman.me/1onU8Ld | Out-File -Append -NoClobber "PowerPoint Online Keyboard Shortcuts.pdf"
Invoke-WebRequest http://ligman.me/1vM9mwt | Out-File -Append -NoClobber "Project 2013 Keyboard Shortcuts.pdf"
Invoke-WebRequest http://ligman.me/1rB8nl1 | Out-File -Append -NoClobber "Publisher 2013 Keyboard Shortcuts.pdf"
Invoke-WebRequest http://ligman.me/1JDjqUt | Out-File -Append -NoClobber "Security and Privacy For Microsoft Office 2010 Users.pdf"
Invoke-WebRequest http://ligman.me/2tYk9gX | Out-File -Append -NoClobber "Security Incident Management in Microsoft Office 365.pdf"
Invoke-WebRequest http://ligman.me/2tYk9gX | Out-File -Append -NoClobber "Security Incident Management in Microsoft Office 365.pdf"
Invoke-WebRequest http://ligman.me/2sVrsGy | Out-File -Append -NoClobber "SharePoint Online Dedicated & OneDrive for Business Dedicated vNext Service Release.pdf"
Invoke-WebRequest http://ligman.me/1M7Xr5v | Out-File -Append -NoClobber "Skype for Business User Tips & Tricks for Anyone.pdf"
Invoke-WebRequest http://ligman.me/2t3nqXV | Out-File -Append -NoClobber "Switching from Google Apps to Office 365 for business.pdf"
Invoke-WebRequest http://ligman.me/2u2K9aI | Out-File -Append -NoClobber "Tenant Isolation in Microsoft Office 365.pdf"
Invoke-WebRequest http://ligman.me/1vM9H2d | Out-File -Append -NoClobber "Visio 2013 Keyboard Shortcuts.pdf"
Invoke-WebRequest http://ligman.me/2sFsnXy | Out-File -Append -NoClobber "Windows 10 Tips and Tricks.pdf"
Invoke-WebRequest http://ligman.me/1m6xucg | Out-File -Append -NoClobber "Word 2013 Keyboard Shortcuts.pdf"
Invoke-WebRequest http://ligman.me/1qzRntH | Out-File -Append -NoClobber "Word Online Keyboard Shortcuts.pdf"
Invoke-WebRequest http://ligman.me/1lJmKeW | Out-File -Append -NoClobber "Working with SmartArt Graphics Keyboard Shortcuts.pdf"
Invoke-WebRequest http://ligman.me/2t3HOIt | Out-File -Append -NoClobber "How to plan capacity for embedded analytics with Power BI Premium.pdf"
Invoke-WebRequest http://ligman.me/2tE789y | Out-File -Append -NoClobber "Introducing Microsoft Power BI.pdf"
Invoke-WebRequest http://ligman.me/2sUDY9j | Out-File -Append -NoClobber "Introducing Microsoft Power BI - Mobile.pdf"
Invoke-WebRequest http://ligman.me/2tEI5U4 | Out-File -Append -NoClobber "Microsoft Power BI Premium Whitepaper.pdf"
Invoke-WebRequest http://ligman.me/2uH1kN1 | Out-File -Append -NoClobber "Microsoft Dynamics GP 2015 R2 PowerShell Users Guide.pdf"
Invoke-WebRequest http://ligman.me/2tY8L4x | Out-File -Append -NoClobber "PowerShell Integrated Scripting Environment 3.0.pdf"
Invoke-WebRequest http://ligman.me/2tyf2TJ | Out-File -Append -NoClobber "Simplify Group Policy administration with Windows PowerShell.pdf"
Invoke-WebRequest http://ligman.me/2v0CY01 | Out-File -Append -NoClobber "Windows PowerShell - Management of Active Directory Infrastructure.pdf"
Invoke-WebRequest http://ligman.me/2v0vXMn | Out-File -Append -NoClobber "Windows PowerShell 3.0 Examples.pdf"
Invoke-WebRequest http://ligman.me/2u8l13d | Out-File -Append -NoClobber "Windows PowerShell 3.0 Language Quick Reference.pdf"
Invoke-WebRequest http://ligman.me/2u8jZEr | Out-File -Append -NoClobber "WINDOWS POWERSHELL 4.0 LANGUAGE QUICK REFERENCE.pdf"
Invoke-WebRequest http://ligman.me/1omCrM6 | Out-File -Append -NoClobber "Windows PowerShell 4.0 Language Reference Examples.pdf"
Invoke-WebRequest http://ligman.me/2sFvbUs | Out-File -Append -NoClobber "Windows PowerShell Command Builder User's Guide.pdf"
Invoke-WebRequest http://ligman.me/2tYmSHb | Out-File -Append -NoClobber "Windows PowerShell Desired State Configuration Quick Reference.pdf"
Invoke-WebRequest http://ligman.me/1n3mkVY | Out-File -Append -NoClobber "WINDOWS POWERSHELL INTEGRATED SCRIPTING ENVIRONMENT 4.0.pdf"
Invoke-WebRequest http://ligman.me/2tEXUKw | Out-File -Append -NoClobber "Windows PowerShell Web Access.pdf"
Invoke-WebRequest http://ligman.me/2tEAt3Z | Out-File -Append -NoClobber "WMI in PowerShell 3.0.pdf"
Invoke-WebRequest http://ligman.me/2t3uPGw | Out-File -Append -NoClobber "WMI in Windows PowerShell 4.0.pdf"
Invoke-WebRequest http://ligman.me/2uFTByu | Out-File -Append -NoClobber "Configuring Microsoft SharePoint Hybrid Capabilities.pdf"
Invoke-WebRequest http://ligman.me/2tXvePt | Out-File -Append -NoClobber "Configuring Microsoft SharePoint Hybrid Capabilities - Mobile.pdf"
Invoke-WebRequest http://ligman.me/12FIZ1I | Out-File -Append -NoClobber "Deployment guide for Microsoft SharePoint 2013.pdf"
Invoke-WebRequest http://ligman.me/2v0Dhb1 | Out-File -Append -NoClobber "Microsoft SharePoint Server 2016 Architectural Models.pdf"
Invoke-WebRequest http://ligman.me/2u0QCD2 | Out-File -Append -NoClobber "Planning and Preparing for Microsoft SharePoint Hybrid - 8.5 X 11.pdf"
Invoke-WebRequest http://ligman.me/2sEzMGA | Out-File -Append -NoClobber "Planning and Preparing for Microsoft SharePoint Hybrid - Mobile.pdf"
Invoke-WebRequest http://ligman.me/2u8h5PG | Out-File -Append -NoClobber "RAP as a Service for SharePoint Server.pdf"
Invoke-WebRequest http://ligman.me/2uGN9ao | Out-File -Append -NoClobber "SharePoint Online Dedicated Service Description.pdf"
Invoke-WebRequest http://ligman.me/TL3pn1 | Out-File -Append -NoClobber "SharePoint Products Keyboard Shortcuts.pdf"
Invoke-WebRequest http://ligman.me/2txHeGo | Out-File -Append -NoClobber "SharePoint Server 2016 Databases - Quick Reference Guide.pdf"
Invoke-WebRequest http://ligman.me/29FkNr3 | Out-File -Append -NoClobber "SharePoint Server 2016 Quick Start Guide.pdf"
Invoke-WebRequest http://ligman.me/1anyEJj | Out-File -Append -NoClobber "5 Tips For A Smooth SSIS Upgrade to SQL Server 2012.pdf"
Invoke-WebRequest http://ligman.me/N1HEpM | Out-File -Append -NoClobber "Backup and Restore of SQL Server Databases.pdf"
Invoke-WebRequest http://ligman.me/2sVpUwk | Out-File -Append -NoClobber "Data Science with Microsoft SQL Server 2016.pdf"
Invoke-WebRequest http://ligman.me/2u8ao0i | Out-File -Append -NoClobber "Deeper insights across data with SQL Server 2016 - Technical White Paper.pdf"
Invoke-WebRequest http://ligman.me/1ReR3Qq | Out-File -Append -NoClobber "Guide to Migrating from Oracle to SQL Server 2014 and Azure SQL Database.pdf"
Invoke-WebRequest http://ligman.me/1RWzIGZ | Out-File -Append -NoClobber "Introducing Microsoft Azure HDInsight.pdf"
Invoke-WebRequest http://ligman.me/2u2j5sf | Out-File -Append -NoClobber "Introducing Microsoft Data Warehouse Fast Track for SQL Server 2016.pdf"
Invoke-WebRequest http://ligman.me/1gfab07 | Out-File -Append -NoClobber "Introducing Microsoft SQL Server 2012.pdf"
Invoke-WebRequest http://ligman.me/1C7dU9J | Out-File -Append -NoClobber "Introducing Microsoft SQL Server 2014.pdf"
Invoke-WebRequest http://ligman.me/2u7ml6r | Out-File -Append -NoClobber "Introducing Microsoft SQL Server 2016 Mission-Critical Applications, Deeper Insights, Hyperscale Cloud, Preview 2.pdf"
Invoke-WebRequest http://ligman.me/2t2o340 | Out-File -Append -NoClobber "Introducing Microsoft SQL Server 2016 Mission-Critical Applications, Deeper Insights, Hyperscale Cloud, Preview 2 - Mobile.pdf"
Invoke-WebRequest http://ligman.me/1KyNJvs | Out-File -Append -NoClobber "Introducing Microsoft SQL Server 2008 R2.pdf"
Invoke-WebRequest http://ligman.me/29pcQFA | Out-File -Append -NoClobber "Microsoft SharePoint Server 2016 Reviewer's Guide.pdf"
Invoke-WebRequest http://ligman.me/N1J8A8 | Out-File -Append -NoClobber "Microsoft SQL Server 2012 Tutorials Analysis Services - Data Mining Step-by-Step.pdf"
Invoke-WebRequest http://ligman.me/N1JfvI | Out-File -Append -NoClobber "Microsoft SQL Server 2012 Tutorials Analysis Services - Multidimensional Modeling Step-by-Step.pdf"
Invoke-WebRequest http://ligman.me/16E6G9L | Out-File -Append -NoClobber "Microsoft SQL Server 2012 Tutorials Reporting Services Quick Step-by-Step.pdf"
Invoke-WebRequest http://ligman.me/16dHXZ9 | Out-File -Append -NoClobber "Microsoft SQL Server 2012 Tutorials Writing Transact-SQL-Statements.pdf"
Invoke-WebRequest http://ligman.me/1S1f34H | Out-File -Append -NoClobber "Microsoft SQL Server 2014 Licensing Guide.pdf"
Invoke-WebRequest http://ligman.me/2sFqolM | Out-File -Append -NoClobber "Microsoft SQL Server 2016 Licensing Datasheet.pdf"
Invoke-WebRequest http://ligman.me/2tEHwtq | Out-File -Append -NoClobber "Microsoft SQL Server 2016 Licensing Guide.pdf"
Invoke-WebRequest http://ligman.me/2uGQTc7 | Out-File -Append -NoClobber "Microsoft SQL Server 2016 Mission-Critical Performance Technical White Paper.pdf"
Invoke-WebRequest http://ligman.me/2u7TbUy | Out-File -Append -NoClobber "Microsoft SQL Server 2016 New Innovations.pdf"
Invoke-WebRequest http://ligman.me/2tYmEzR | Out-File -Append -NoClobber "Microsoft SQL Server 2016 SP1 Editions.pdf"
Invoke-WebRequest http://ligman.me/2tYaW8d | Out-File -Append -NoClobber "Microsoft SQL Server In-Memory OLTP and Columnstore Feature Comparison.pdf"
Invoke-WebRequest http://ligman.me/2u2HKg6 | Out-File -Append -NoClobber "RAP as a Service for SQL Server.pdf"
Invoke-WebRequest http://ligman.me/2tEHLVm | Out-File -Append -NoClobber "SQLCAT's Guide to Relational Engine.pdf"
Invoke-WebRequest http://ligman.me/11IMDlh | Out-File -Append -NoClobber "Xquery Language Reference.pdf"
Invoke-WebRequest http://ligman.me/29i2CEe | Out-File -Append -NoClobber "Surface Book User Guide.pdf"
Invoke-WebRequest http://ligman.me/29hofVk | Out-File -Append -NoClobber "Surface Pro 4 User Guide.pdf"
Invoke-WebRequest http://ligman.me/1dD6S0J | Out-File -Append -NoClobber "Introducing Microsoft System Center 2012 R2.pdf"
Invoke-WebRequest http://ligman.me/2sUch05 | Out-File -Append -NoClobber "Microsoft System Center Building a Virtualized Network Solution, Second Edition.pdf"
Invoke-WebRequest http://ligman.me/1JDrhBp | Out-File -Append -NoClobber "Microsoft System Center Data Protection for the Hybrid Cloud.pdf"
Invoke-WebRequest http://ligman.me/1C7okGv | Out-File -Append -NoClobber "Microsoft System Center Deploying Hyper-V with Software-Defined Storage & Networking.pdf"
Invoke-WebRequest http://ligman.me/1KBVfnS | Out-File -Append -NoClobber "Microsoft System Center Extending Operations Manager Reporting.pdf"
Invoke-WebRequest http://ligman.me/1IzHZA1 | Out-File -Append -NoClobber "Microsoft System Center Introduction to Microsoft Automation Solutions.pdf"
Invoke-WebRequest http://ligman.me/1GUUqSD | Out-File -Append -NoClobber "Microsoft System Center Operations Manager Field Experience.pdf"
Invoke-WebRequest http://ligman.me/1CQXNbj | Out-File -Append -NoClobber "Microsoft System Center Software Update Management Field Experience.pdf"
Invoke-WebRequest http://ligman.me/1GUOZ6b | Out-File -Append -NoClobber "Microsoft System Center Building a Virtualized Network Solution.pdf"
Invoke-WebRequest http://ligman.me/1GUP0qL | Out-File -Append -NoClobber "Microsoft System Center Cloud Management with App Controller.pdf"
Invoke-WebRequest http://ligman.me/1KBMN8a | Out-File -Append -NoClobber "Microsoft System Center Configuration Manager Field Experience.pdf"
Invoke-WebRequest http://ligman.me/1f9cKQZ | Out-File -Append -NoClobber "Microsoft System Center Designing Orchestrator Runbooks.pdf"
Invoke-WebRequest http://ligman.me/1gfaIzh | Out-File -Append -NoClobber "Microsoft System Center Integrated Cloud Platform.pdf"
Invoke-WebRequest http://ligman.me/1JIF6vB | Out-File -Append -NoClobber "Microsoft System Center Network Virtualization and Cloud Computing.pdf"
Invoke-WebRequest http://ligman.me/1M00Lzu | Out-File -Append -NoClobber "Microsoft System Center Optimizing Service Manager.pdf"
Invoke-WebRequest http://ligman.me/1M00v3u | Out-File -Append -NoClobber "Microsoft System Center Troubleshooting Configuration Manager.pdf"
Invoke-WebRequest http://ligman.me/2t3NaDl | Out-File -Append -NoClobber "What's new in System Center 2016 White Paper.pdf"
Invoke-WebRequest http://ligman.me/1eql6Ts | Out-File -Append -NoClobber "Understanding Microsoft Virtualizaton R2 Solutions.pdf"
Invoke-WebRequest http://ligman.me/2sE9XX1 | Out-File -Append -NoClobber "Deploying Windows 10 Automating deployment by using System Center Configuration Manager.pdf"
Invoke-WebRequest http://ligman.me/2twLeqF | Out-File -Append -NoClobber "Deploying Windows 10 Automating deployment by using System Center Configuration Manager - Mobile.pdf"
Invoke-WebRequest http://ligman.me/2t2WmYx | Out-File -Append -NoClobber "Introducing Windows 10 for IT Professionals.pdf"
Invoke-WebRequest http://ligman.me/1Uiyx8Q | Out-File -Append -NoClobber "Introducing Windows 10 for IT Professionals, Preview Edition.pdf"
Invoke-WebRequest http://ligman.me/1JDrMeG | Out-File -Append -NoClobber "Introducing Windows 8.1 for IT Professionals.pdf"
Invoke-WebRequest http://ligman.me/1GVGQgI | Out-File -Append -NoClobber "Introducing Windows 8 An Overview for IT Professionals.pdf"
Invoke-WebRequest http://ligman.me/2txIfxW | Out-File -Append -NoClobber "Licensing Windows desktop operating system for use with virtual machines.pdf"
Invoke-WebRequest http://ligman.me/2u2R83b | Out-File -Append -NoClobber "RAP as a Service for Windows Desktop.pdf"
Invoke-WebRequest http://ligman.me/2sFzkaR | Out-File -Append -NoClobber "Volume Licensing Reference Guide Windows 10 Desktop Operating System.pdf"
Invoke-WebRequest http://ligman.me/2u12Nj7 | Out-File -Append -NoClobber "Windows 10 IT Pro Essentials Support Secrets.pdf"
Invoke-WebRequest http://ligman.me/2uFUOG1 | Out-File -Append -NoClobber "Windows 10 IT Pro Essentials Support Secrets.pdf"
Invoke-WebRequest http://ligman.me/2t2cYjp | Out-File -Append -NoClobber "Windows 10 IT Pro Essentials Top 10 Tools.pdf"
Invoke-WebRequest http://ligman.me/2u15CAR | Out-File -Append -NoClobber "Windows 10 IT Pro Essentials Top 10 Tools - Mobile.pdf"
Invoke-WebRequest http://ligman.me/1sfkqBW | Out-File -Append -NoClobber "Work Smart Windows 8 Shortcut Keys.pdf"
Invoke-WebRequest http://ligman.me/1FYVYcy | Out-File -Append -NoClobber "Introducing Windows Server 2008 R2.pdf"
Invoke-WebRequest http://ligman.me/1M0681D | Out-File -Append -NoClobber "Introducing Windows Server 2012.pdf"
Invoke-WebRequest http://ligman.me/1NCxHi5 | Out-File -Append -NoClobber "Introducing Windows Server 2012 R2.pdf"
Invoke-WebRequest http://ligman.me/2uFKRZd | Out-File -Append -NoClobber "Introducing Windows Server 2016.pdf"
Invoke-WebRequest http://ligman.me/2tDMJl0 | Out-File -Append -NoClobber "Introducing Windows Server 2016 - Mobile.pdf"
Invoke-WebRequest http://ligman.me/2uFDelL | Out-File -Append -NoClobber "Introducing Windows Server 2016 Technical Preview.pdf"
Invoke-WebRequest http://ligman.me/2twmtKY | Out-File -Append -NoClobber "Introducing Windows Server 2016 Technical Preview - Mobile.pdf"
Invoke-WebRequest http://ligman.me/1f9k8fe | Out-File -Append -NoClobber "Introducing Windows Server 2012 R2 Preview Release.pdf"
Invoke-WebRequest http://ligman.me/2v1cDyG | Out-File -Append -NoClobber "Offline Assessment for Active Directory.pdf"
Invoke-WebRequest http://ligman.me/2txRQFd | Out-File -Append -NoClobber "RAP as a Service for Active Directory.pdf"
Invoke-WebRequest http://ligman.me/2v1zdYa | Out-File -Append -NoClobber "RAP as a Service for Failover Cluster.pdf"
Invoke-WebRequest http://ligman.me/2sW0A9v | Out-File -Append -NoClobber "RAP as a Service for Internet Information Services.pdf"
Invoke-WebRequest http://ligman.me/2txQLgl | Out-File -Append -NoClobber "RAP as a Service for Windows Server Hyper-V.pdf"
Invoke-WebRequest http://ligman.me/2sFbVq3 | Out-File -Append -NoClobber "Windows Server 2016 Licensing.pdf"
